# Generated by Django 3.0.3 on 2020-04-26 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='country',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='language',
            field=models.CharField(blank=True, choices=[('T', 'Telugu'), ('E', 'English'), ('H', 'Hindi')], max_length=1, null=True),
        ),
    ]
